backend:
  name: github
  repo: StanGirard/Primates
  branch: master
  open_authoring: true

publish_mode: editorial_workflow

media_folder: "assets/images"

collections:
  - name: "Articles"
    label: "Articles"
    folder: "_posts"
    create: true
    editor:
      preview: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    preview_path: "{{title}}"
    fields: # The fields for each document, usually in front matter.
      - {label: "Layout", name: "layout", widget: "hidden", default: "post"}
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Description", name: "description", widget: "text"}
      - {label: "Categories", name: "categories",widget: "list", required: true}
      - {label: "Image", name: "image", widget: "image", required: true}
      - {label: 'Author',name: 'author',widget: 'relation',collection: 'authors',displayFields: [display_name],searchFields: [display_name],valueField: 'name',multiple: true}
      - {label: "Commentary", name: "commentary", widget: "text", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: 'authors'
    label: 'Authors'
    folder: '_authors/'
    create: true
    editor:
      preview: true
    fields: # The fields for each document, usually in front matter
      - {label: "Layout", name: "layout", widget: "hidden", default: "page"}
      - {label: "Title Author Page", name: "title", widget: "string", required: true}
      - {label: "Description", name: "description", widget: "string",required: true}
      - {label: "username", name: "name", widget: "string"}
      - {label: "Display Name", name: "display_name", widget: "string"}
      - {label: "Email", name: "email", widget: "string", required: false}
      - {label: "Website", name: "web", widget: "string"}
      - {label: "GitHub Username",name: "github_username",widget: "string",required: false}
      - {label: "Facebook Username",name: "facebook_username",widget: "string",required: false}
      - {label: "Twitter Username",name: "twitter",widget: "string",required: false}
      - {label: "LinkedIn Username",name: "linkedin_username",widget: "string",required: false}
      - {label: "Body", name: "body", widget: "markdown"}